### ISSUE TITLE
ERROR: error during handshake: error on replay: Wrong Block.Header.AppHash.  Expected A74D98958D7A6D4EDFFBBF760EDE9A27DF9141A379DBB1E55F5A6AF71C5D3A2C, got 1F7F6326657EB801001C4E49848D882551B3F2B4CA1259CF533E3F1BE8AFD339

### ISSUE THREAD

**Issue by IvanDedov** [binance-chain/node-binary#204] opened 2020-05-30 10:37 UTC
Hi guys!
Node stopped working

spec is like below:

OS: Ubuntu 16.04.6 LTS

version: Binance Chain Release: 0.6.3-hf.1;Binance Chain Commit: a5abb0f; Cosmos Release: v0.25.0-binance.21; Tendermint Release: v0.32.3-binance.1;

config.toml

fast_sync = true
state_sync_reactor = true
state_sync_height = 0
hot_sync = true
hot_sync_timeout = "3s"
hot_sync_reactor = true

---------------
Startup error

bnb@bcs:~$ /usr/local/bin/bnbchaind start --home /srv/HDD4/home/bnb/.bnbchaind --pruning breathe&
[1] 32547
bnb@bcs:~$ panic: Failed to process committed block (90913099:6EAF26E7AA83DD2B2513CA432793847B50E8243EDBBF992BB79D8C2568F6FEDA): Wrong Block.Header.AppHash.  Expected A74D98958D7A6D4EDFFBBF760EDE9A27DF9141A379DBB1E55F5A6AF71C5D3A2C, got 1F7F6326657EB801001C4E49848D882551B3F2B4CA1259CF533E3F1BE8AFD339

goroutine 36949 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc0152ca340)
        /home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.1/blockchain/v0/reactor.go:399 +0x1bf0
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
        /home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.1/blockchain/v0/reactor.go:126 +0x84

**Comment by jseibel-circle** [comment] 2020-05-30 10:54
Same issue for me

**Comment by Alteryy** [comment] 2020-05-30 12:22
I have the exact same error.
./state_recover 90913098 dose not work.

**Comment by guagualvcha** [comment] 2020-05-30 15:14
Hi, can you also post the app.toml file here as well.

**Comment by HaoyangLiu** [comment] 2020-05-30 15:17
@IvanDedov Could you share your `app.toml`

**Comment by guagualvcha** [comment] 2020-05-30 15:23
> I have the exact same error.
> ./state_recover 90913098 dose not work.
Before we locate the root cause, can you try with `./state_recover 90913097` and feed back here? Thanks @Alteryy

**Comment by IvanDedov** [comment] 2020-05-30 15:23
# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

[base]
# Interval blocks of breathe block, if breatheBlockInterval is 0, breathe block will be created every day.
breatheBlockInterval = 0
# Size of account cache
accountCacheSize = 30000
# Size of signature cache
signatureCacheSize = 30000
# Running mode when start up, 0: Normal, 1: TransferOnly, 2: RecoverOnly
startMode = 0
# Concurrency of OrderKeeper, should be power of 2
orderKeeperConcurrency = 2
# Days count back for breathe block
breatheBlockDaysCountBack = 7

[upgrade]
# Block height of BEP6 upgrade
BEP6Height = 20300000
# Block height of BEP9 upgrade
BEP9Height = 20300000
# Block height of BEP10 upgrade
BEP10Height = 20300000
# Block height of BEP19 upgrade
BEP19Height = 20300000
# Block height of BEP12 upgrade
BEP12Height = 25120000
# Block height of BEP3 upgrade
BEP3Height = 41277000
# Block height of FixSignBytesOverflow upgrade
FixSignBytesOverflowHeight = 51467800
# Block height of LotSizeOptimization upgrade
LotSizeUpgradeHeight = 51467800
# Block height of changing listing rule upgrade
ListingRuleUpgradeHeight = 51467800
# Block height of FixZeroBalanceHeight upgrade
FixZeroBalanceHeight = 51467800

[addr]
# Bech32PrefixAccAddr defines the Bech32 prefix of an account's address
bech32PrefixAccAddr = "bnb"
# Bech32PrefixAccPub defines the Bech32 prefix of an account's public key
bech32PrefixAccPub = "bnbp"
# Bech32PrefixValAddr defines the Bech32 prefix of a validator's operator address
bech32PrefixValAddr = "bva"
# Bech32PrefixValPub defines the Bech32 prefix of a validator's operator public key
bech32PrefixValPub = "bvap"
# Bech32PrefixConsAddr defines the Bech32 prefix of a consensus node address
bech32PrefixConsAddr = "bca"
# Bech32PrefixConsPub defines the Bech32 prefix of a consensus node public key
bech32PrefixConsPub = "bcap"

##### publication related configurations #####
[publication]
# configurations ends with Kafka can be a semi-colon separated host-port list
# Whether we want publish market data (this includes trades and order)
publishOrderUpdates = true
orderUpdatesTopic = "orders"
orderUpdatesKafka = "127.0.0.1:9092"

# Whether we want publish account balance to notify browser db indexer persist latest account balance change
publishAccountBalance = true
accountBalanceTopic = "accounts"
accountBalanceKafka = "127.0.0.1:9092"

# Whether we want publish order book changes
publishOrderBook = true
orderBookTopic = "orders"
orderBookKafka = "127.0.0.1:9092"

# Whether we want publish block fee changes
publishBlockFee = true
blockFeeTopic = "accounts"
blockFeeKafka = "127.0.0.1:9092"

# Whether we want publish transfers
publishTransfer = true
transferTopic = "transfers"
transferKafka = "127.0.0.1:9092"

# Global setting
publicationChannelSize = "10000"
publishKafka = false
publishLocal = true
# max size in megabytes of marketdata json file before rotate
localMaxSize = 1024
# max days of marketdata json files to keep before deleted
localMaxAge = 7

[log]

# Write logs to console instead of file
logToConsole = false

## The below parameters take effect only when logToConsole is false
# Log file root, if not set, use home path
logFileRoot = ""
# Log file path relative to log file root path
logFilePath = "bnc.log"
# Number of logs keep in memory before writing to file
logBuffSize = 10000

**Comment by IvanDedov** [comment] 2020-05-30 15:26
> > I have the exact same error.
> > ./state_recover 90913098 dose not work.
> 
> Before we locate the root cause, can you try with `./state_recover 90913097` and feed back here? Thanks @Alteryy

bnb@bcs:~$ ./state_recover 90913097 /srv/HDD4/home/bnb/.bnbchaind
recover home_path[/srv/HDD4/home/bnb/.bnbchaind] to height[90913097]
recover success
bnb@bcs:~$ /usr/local/bin/bnbchaind start --home /srv/HDD4/home/bnb/.bnbchaind --pruning breathe&
[1] 29150
bnb@bcs:~$ panic: Failed to process committed block (90913099:6EAF26E7AA83DD2B2513CA432793847B50E8243EDBBF992BB79D8C2568F6FEDA): Wrong Block.Header.AppHash.  Expected A74D98958D7A6D4EDFFBBF760EDE9A27DF9141A379DBB1E55F5A6AF71C5D3A2C, got 1F7F6326657EB801001C4E49848D882551B3F2B4CA1259CF533E3F1BE8AFD339

goroutine 36896 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc01554a4e0)
        /home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.1/blockchain/v0/reactor.go:399 +0x1bf0
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
        /home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.1/blockchain/v0/reactor.go:126 +0x84

[1]+  Exit 2                  /usr/local/bin/bnbchaind start --home /srv/HDD4/home/bnb/.bnbchaind --pruning breathe

**Comment by HaoyangLiu** [comment] 2020-05-30 15:28
Could you execute `df -h` to show your disk information?

**Comment by IvanDedov** [comment] 2020-05-30 15:41
> Could you execute `df -h` to show your disk information?

bnb@bcs:~$ df -h
Filesystem                   Size  Used Avail Use% Mounted on
udev                          32G     0   32G   0% /dev
tmpfs                        6.3G  642M  5.7G  11% /run
/dev/mapper/ubuntu--vg-root  457G   96G  338G  23% /
tmpfs                         32G     0   32G   0% /dev/shm
tmpfs                        5.0M     0  5.0M   0% /run/lock
tmpfs                         32G     0   32G   0% /sys/fs/cgroup
/dev/sda1                    459G  306G  130G  71% /srv/HDD1
/dev/sdb1                    459G  382G   54G  88% /srv/HDD2
/dev/sde1                    3.6T  583G  2.9T  17% /srv/HDD4
/dev/sdc1                    220G   88G  122G  42% /srv/HDD3
/dev/sdd2                    721M  190M  495M  28% /boot
/dev/sdd1                    511M  3.6M  508M   1% /boot/efi

**Comment by HaoyangLiu** [comment] 2020-05-30 15:49
Try these steps:
- Delete `addrbook.json`
- Empty seed and  persistent_peers in `config.toml`
```
# Comma separated list of seed nodes to connect to
seeds = ""

# Comma separated list of nodes to keep persistent connections to
persistent_peers = ""
```
- `./state_recover 90913098`
- Start node again
- Execute this command and share the response
```
curl localhost:26657/block_results?height=90913098
```

**Comment by IvanDedov** [comment] 2020-05-30 16:18
bnb@bcs:/srv/HDD4/home# curl localhost:26657/block_results?height=90913098
{
  "jsonrpc": "2.0",
  "id": "",
  "error": {
    "code": -32603,
    "message": "Internal error",
    "data": "Height must be less than or equal to the current blockchain height"
  }

**Comment by IvanDedov** [comment] 2020-05-30 16:31
bnb@bcs:/srv/HDD4/home# tail -f /srv/HDD4/home/bnb/.bnbchaind/bnc.log
I[2020-05-30|19:16:43.368] ABCI Handshake App Info                      module=consensus height=90913098 hash=A74D98958D7A6D4EDFFBBF760EDE9A27DF9141A379DBB1E55F5A6AF71C5D3A2C software-version= protocol-version=0
I[2020-05-30|19:16:43.368] ABCI Replay Blocks                           module=consensus appHeight=90913098 storeHeight=90913098 stateHeight=90913098
I[2020-05-30|19:16:43.368] Completed ABCI Handshake - Tendermint and App are synced module=consensus appHeight=90913098 appHash=A74D98958D7A6D4EDFFBBF760EDE9A27DF9141A379DBB1E55F5A6AF71C5D3A2C
I[2020-05-30|19:16:43.368] This node is not a validator                 module=consensus addr=B4F6003531C336F2EED86DDD668D4A8B2C31B9F2 pubKey=PubKeyEd25519{C1B26FF8FB267F8DD40BB9CE07570CF52E1DDA7DF1470ED42B466780057888A3}
I[2020-05-30|19:16:43.410] Starting BlockchainReactor                   module=blockchain impl=BlockchainReactor
I[2020-05-30|19:16:43.410] Starting BlockPool                           module=blockchain impl=BlockPool
I[2020-05-30|19:16:43.410] Starting ConsensusReactor                    module=consensus impl=ConsensusReactor
I[2020-05-30|19:16:43.410] ConsensusReactor                             module=consensus fastSync=true
I[2020-05-30|19:16:43.410] Starting StateSyncReactor                    module=statesync impl=StateSyncReactor
I[2020-05-30|19:16:43.410] This node does not need state sync, it might has already state synced, please check module=statesync lockfile=STATESYNC.LOCK

**Comment by IvanDedov** [comment] 2020-05-30 17:01
> Try these steps:
> 
> * Delete `addrbook.json`
> * Empty seed and  persistent_peers in `config.toml`
> 
> ```
> # Comma separated list of seed nodes to connect to
> seeds = ""
> 
> # Comma separated list of nodes to keep persistent connections to
> persistent_peers = ""
> ```
> 
> * `./state_recover 90913098`
> * Start node again, without ` --pruning` flag
> * Execute this command and share the response
> 
> ```
> curl localhost:26657/block_results?height=90913098
> ```

It's all done
What should I do next?

**Comment by huangsuyu** [comment] 2020-05-31 01:21
> bnb@bcs:/srv/HDD4/home# curl localhost:26657/block_results?height=90913098
> {
> "jsonrpc": "2.0",
> "id": "",
> "error": {
> "code": -32603,
> "message": "Internal error",
> "data": "Height must be less than or equal to the current blockchain height"
> }

I think the default port is `27147` for mainnet.

could you please check `curl localhost:27147/status`

**Comment by IvanDedov** [comment] 2020-05-31 05:34
> > bnb@bcs:/srv/HDD4/home# curl localhost:26657/block_results?height=90913098
> > {
> > "jsonrpc": "2.0",
> > "id": "",
> > "error": {
> > "code": -32603,
> > "message": "Internal error",
> > "data": "Height must be less than or equal to the current blockchain height"
> > }
> 
> I think the default port is `27147` for mainnet.
> 
> could you please check `curl localhost:27147/status`

bnb@bcs:/srv/HDD4/home# curl localhost:27147/status
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "node_info": {
      "protocol_version": {
        "p2p": "7",
        "block": "10",
        "app": "0"
      },
      "id": "1969aa323aa02f990cf934a7a7905456ab533b5d",
      "listen_addr": "tcp://0.0.0.0:27146",
      "network": "Binance-Chain-Tigris",
      "version": "0.32.3",
      "channels": "36402021222330380041",
      "moniker": "xxx",
      "other": {
        "tx_index": "on",
        "rpc_address": "tcp://0.0.0.0:27147"
      }
    },
    "sync_info": {
      "latest_block_hash": "B6562C89B41CD77A86D36C7C8CADFB3A5A70D86E5D51A99B6D57CE9A0EFF53D7",
      "latest_app_hash": "28E0E03608674241985DACA5E05266EA7BE84CD3A6CD36C2961B88A9140E6762",
      "latest_block_height": "90913098",
      "latest_block_time": "2020-05-30T02:22:59.967462567Z",
      "catching_up": true,
      "index_height": "90913098"
    },
    "validator_info": {
      "address": "B4F6003531C336F2EED86DDD668D4A8B2C31B9F2",
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "wbJv+Psmf43UC7nOB1cM9S4d2n3xRw7UK0ZngAV4iKM="
      },
      "voting_power": "0"
    }
  }

**Comment by IvanDedov** [comment] 2020-05-31 05:35
root@bcs:/srv/HDD4/home# curl localhost:27147/block_results?height=90913098
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "height": "90913098",
    "results": {
      "DeliverTx": [
        {
          "data": "l6VrjbBq3g/ZoX5SYDhkAanVAN/glhIg/5BAaOnph18=",
          "log": "Msg 0: swapID: 97a56b8db06ade0fd9a17e5260386401a9d500dfe0961220ff904068e9e9875f",
          "events": [
            {
              "attributes": [
                {
                  "key": "c2VuZGVy",
                  "value": "Ym5iMWNndjdjcmg2cmM5NHU1Y24wZGt2ajY3ZjNzYXdzZmhuNzI4dHFj"
                },
                {
                  "key": "cmVjaXBpZW50",
                  "value": "Ym5iMXd4ZXBseXc3eDhhYWh5OTN3OTZ5aHdtN3hjcTNrZTRmOGdlOTN1"
                },
                {
                  "key": "YWN0aW9u",
                  "value": "SFRMVA=="
                }
              ]
            }
          ]
        }
      ],
      "EndBlock": {
        "validator_updates": null,
        "events": [
          {}
        ]
      },
      "BeginBlock": {}
    }
  }

**Comment by Alteryy** [comment] 2020-05-31 07:36
> > bnb@bcs:/srv/HDD4/home# curl localhost:26657/block_results?height=90913098
> > {
> > "jsonrpc": "2.0",
> > "id": "",
> > "error": {
> > "code": -32603,
> > "message": "Internal error",
> > "data": "Height must be less than or equal to the current blockchain height"
> > }
> 
> I think the default port is `27147` for mainnet.
> 
> could you please check `curl localhost:27147/status`

{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "node_info": {
      "protocol_version": {
        "p2p": "7",
        "block": "10",
        "app": "0"
      },
      "id": "76c8a057f0bbbe36dfb0894baa6fac1fe2bc1a25",
      "listen_addr": "tcp://0.0.0.0:27146",
      "network": "Binance-Chain-Tigris",
      "version": "0.32.3",
      "channels": "364020212223303800",
      "moniker": "xxx",
      "other": {
        "tx_index": "on",
        "rpc_address": "tcp://0.0.0.0:27147"
      }
    },
    "sync_info": {
      "latest_block_hash": "B6562C89B41CD77A86D36C7C8CADFB3A5A70D86E5D51A99B6D57CE9A0EFF53D7",
      "latest_app_hash": "28E0E03608674241985DACA5E05266EA7BE84CD3A6CD36C2961B88A9140E6762",
      "latest_block_height": "90913098",
      "latest_block_time": "2020-05-30T02:22:59.967462567Z",
      "catching_up": true,
      "index_height": "90913098"
    },
    "validator_info": {
      "address": "51568DA4F18EE3BCEDB7E9BA7D9C0134A106430B",
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "0FGUPBKb9CD/jIKPEy2KWB/6Rfx5kMqrOtvym6V9Spo="
      },
      "voting_power": "0"
    }
  }
}

**Comment by Alteryy** [comment] 2020-05-31 15:45
> Same issue for me. Same log message and then node dies and restarts, gets to this point and dies again, repeat forever

Did you solve your problem ?

**Comment by jseibel-circle** [comment] 2020-06-01 03:43
> > Same issue for me. Same log message and then node dies and restarts, gets to this point and dies again, repeat forever
> 
> Did you solve your problem ?

No

**Comment by huangsuyu** [comment] 2020-06-01 07:04
@Alteryy @jseibel-circle @IvanDedov Hello, guys! a hotfix will be released to fix this sync issue. I will keep you updated

**Comment by Alteryy** [comment] 2020-06-01 08:36
> > > Same issue for me. Same log message and then node dies and restarts, gets to this point and dies again, repeat forever
> > 
> > 
> > Did you solve your problem ?
> 
> No

After I backed up the data folder, I restarted the node, and it would be fine in a day

**Comment by IvanDedov** [comment] 2020-06-01 08:52
> @Alteryy @jseibel-circle @IvanDedov Hello, guys! a hotfix will be released to fix this sync issue. I will keep you updated

Thank you for your active work in solving this problem. Waiting for fix

**Comment by jseibel-circle** [comment] 2020-06-01 15:51
We upgraded our binary, still have the same issue. Is there anything else necessary but the binary? We need the full historical data

**Comment by IvanDedov** [comment] 2020-06-01 21:08
Updating with the installation script "install.sh" does not lead to the installation of a new binary package 0.6.3-hf.2.
bnb @ bcs: ~ $ / usr / local / bin / bnbchaind version
Binance Chain Release: 0.6.3-hf.1; Binance Chain Commit: a5abb0f; Cosmos Release: v0.25.0-binance.21; Tendermint Release: v0.32.3-binance.1;

Old 0.6.3-hf.1 is installed

**Comment by jseibel-circle** [comment] 2020-06-02 00:49
We were able to solve the issue using the new hotfix release. We don't use install.sh

We updated the binary, then used:

`state_recover 90913097 [home directory]`

Notice how we used 90913097, which is one less than the error block.

Then we started the node with `--pruning breathe` flag, and it was able to get past the broken block.

**Comment by huangsuyu** [comment] 2020-06-02 03:55
@Alteryy @jseibel-circle @IvanDedov Hello, guys! As you may notice, a [hotfix: 0.6.3-hotfix-2](https://github.com/binance-chain/node-binary/tree/master/fullnode/prod/0.6.3-hotfix-2) for this issue is now available.  please follow the following instructions to get it back online

- Download the tool: [state-recover](https://github.com/binance-chain/node-binary/tree/master/tools/recover)
- Backup your home directory
- run the following command to recover the state to just one block before the crash, which is 90913097:
```
./state_recover 90913097 <your_home_path>
```
- Restart with the version v0.6.3-hf.2 of bnbchaind
```
bnbchaind start --home <home-path>
```

**Comment by IvanDedov** [comment] 2020-06-02 07:26
> @Alteryy @jseibel-circle @IvanDedov Hello, guys! As you may notice, a [hotfix: 0.6.3-hotfix-2](https://github.com/binance-chain/node-binary/tree/master/fullnode/prod/0.6.3-hotfix-2) for this issue is now available. please follow the following instructions to get it back online
> 
> * Download the tool: [state-recover](https://github.com/binance-chain/node-binary/tree/master/tools/recover)
> * Backup your home directory
> * run the following command to recover the state to just one block before the crash, which is 90913097:
> 
> ```
> ./state_recover 90913097 <your_home_path>
> ```
> 
> * Restart with the version v0.6.3-hf.2 of bnbchaind
> 
> ```
> bnbchaind start --home <home-path>
> ```

Did everything as they wrote. The node started. Thank you!
Request can be closed.

**Comment by wyh00544** [comment] 2020-07-09 10:00
<img width="1085" alt="图片" src="https://user-images.githubusercontent.com/22042043/87026150-ea54a280-c20d-11ea-90d1-41665a306e94.png">
According to this treatment, the same error is reported @huangsuyu

**Comment by mahsumurebe** [comment] 2020-07-09 20:33
Where can I get the block height before the situation crashes?

**Comment by huangsuyu** [comment] 2020-07-10 02:06
> <img alt="图片" width="1085" src="https://user-images.githubusercontent.com/22042043/87026150-ea54a280-c20d-11ea-90d1-41665a306e94.png">
> 
> According to this treatment, the same error is reported @huangsuyu

please rever to 1 block before upgrade height: 99549999.
```
./state_recover 99549999 <home folder>
```

**Comment by wyh00544** [comment] 2020-07-10 02:36
@huangsuyu 

My dirty block is 99550001, so I should use.

./state_recover 99550000 <home folder>

**Comment by huangsuyu** [comment] 2020-07-10 03:13
> @huangsuyu
> 
> My dirty block is 99550001, so I should use.
> 
> ./state_recover 99550000

You have to revert before the upgrade height to activate new logic.

**Comment by wyh00544** [comment] 2020-07-10 08:52
You can't do this. I need to delete and resynchronize data, but the same problem happened in the middle .
@huangsuyu

**Comment by mahsumurebe** [comment] 2020-07-11 11:31
This problem is constantly repeating. I find the dirty block number in the bnc.log file and run the state_recover binary using the dirty block number. I then replace the BEP3Height value in the app.toml file with the dirty block number. This error occurs continuously without 10k block sync.

**Comment by huangsuyu** [comment] 2020-07-12 02:48
> This problem is constantly repeating. I find the dirty block number in the bnc.log file and run the state_recover binary using the dirty block number. I then replace the BEP3Height value in the app.toml file with the dirty block number. This error occurs continuously without 10k block sync.

Please do not change any value in `app.toml `

Please double check your open file limits and set it to 65536
```
ulimit -n 65535
```
just revert to 1 block before the crash height then restart

**Closed** 2020-07-16 06:24 UTC

**Comment by mahsumurebe** [comment] 2020-07-16 19:48
> > This problem is constantly repeating. I find the dirty block number in the bnc.log file and run the state_recover binary using the dirty block number. I then replace the BEP3Height value in the app.toml file with the dirty block number. This error occurs continuously without 10k block sync.
> 
> Please do not change any value in `app.toml `
> 
> Please double check your open file limits and set it to 65536
> 
> ```
> ulimit -n 65535
> ```
> 
> just revert to 1 block before the crash height then restart


open file limit was higher than 65535. Now I changed it to 65535. Disruption occurred in the blocks. I deleted the block data. I expect it to be synced again right now. It started to synchronize from the 100 millionth block.

Do I need to update the config.toml, app.toml and genesis.json files with every update?

**Comment by huangsuyu** [comment] 2020-07-17 03:18
> > > This problem is constantly repeating. I find the dirty block number in the bnc.log file and run the state_recover binary using the dirty block number. I then replace the BEP3Height value in the app.toml file with the dirty block number. This error occurs continuously without 10k block sync.
> > 
> > 
> > Please do not change any value in `app.toml `
> > Please double check your open file limits and set it to 65536
> > ```
> > ulimit -n 65535
> > ```
> > 
> > 
> > just revert to 1 block before the crash height then restart
> 
> open file limit was higher than 65535. Now I changed it to 65535. Disruption occurred in the blocks. I deleted the block data. I expect it to be synced again right now. It started to synchronize from the 100 millionth block.
> 
> Do I need to update the config.toml, app.toml and genesis.json files with every update?

not exactly, you must update `app.toml` when updating

**Comment by mahsumurebe** [comment] 2020-08-20 08:52
This error occurs constantly. I have to do the state_recovery process every time. I am constantly waiting for the node to synchronize. But it doesn't synchronize at all. Will a fix be released for this?

**Comment by aliRamshini72** [comment] 2022-01-29 11:25
ERROR: error during handshake: error on replay: Wrong Block.Header.AppHash.  Expected 33DE1D6B12F9654A767F176B1E53C525FB2052ABB9C5264DD997E257E43B8663, got 706D12258C4F5806BBF3B3054D95A530176CC871B6FD7691189832E37003204E
